select = ["E", "W", "F"]

# Исключение некоторых ошибок, если нужно
# Например, E501 (ограничение длины строки) можно отключить, если это не критично
# ignore = ["E501"]

# Ограничение длины строки (по PEP 8 — 79 символов)
line-length = 79

# Автоматическая сортировка импортов (по PEP 8)
# Можно использовать встроенный механизм сортировки isort
fixable = ["I"]

# Включение автоматических исправлений (например, при использовании ruff --fix)
fix = true